name: Deploy project
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v4
      - name: install node js
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: install dependendencies
        run: npm ci
      - name: lint check
        run: npm run lint
      - name: run test
        run: npm test

      - name: build project
        run: npm run build

      - name: deploy job
        run: echo "deploy job successfully"
