name: Deploy project parallel
on: push
jobs:
  getcode:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v4


  
  installall:
    needs: getcode
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v4
      - name: install node js
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: install dependendencies
        run: npm ci



  
  lintcode:
    needs: installall
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v4

      - name: install node js
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: install dependendencies
        run: npm ci
      - name: lint check
        run: npm run lint




  
  testcode:
    needs: lintcode
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v4
      - name: run test
        run: npm test




  deploycode:
    needs: testcode
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v4
      - name: deploy job
        run: echo "deploy job successfully"